name: Run Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        python3 -m poetry install --no-root

    - name: Run Flask App
      run: |
        python3 -m flask run --host=0.0.0.0
