name: Run Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -       

    - name: Add Poetry to PATH
      run: |
        echo 'export PATH="$HOME/.poetry/bin:$PATH"' >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Verify Poetry installation
      run: |
        poetry --version
        
    - name: Install dependencies
      run: |
        python3 -m poetry install --no-root

    - name: Run Flask App
      run: |
        poetry run flask run --host=0.0.0.0
